spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/spring_batch_test
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: true

